name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Build Solution
      run: |
        msbuild.exe VeinClient/VeinClient.sln /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Normal"
        
    - name: Upload VeinClient Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VeinClient.dll
        path: VeinClient/VeinClient/bin/Debug/VeinClient.dll
        
    - name: Upload PlagueButtonAPI PDB Artifact
      uses: actions/upload-artifact@v2
      with:
        name: VeinClient.pdb
        path: VeinClient/VeinClient/bin/Debug/VeinClient.pdb
